ALTER TABLE "Tenant"
  ADD COLUMN IF NOT EXISTS "reminderEnabled" BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS "reminder1Hours"  INTEGER NOT NULL DEFAULT 24,
  ADD COLUMN IF NOT EXISTS "reminder2Hours"  INTEGER NOT NULL DEFAULT 2;
